/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "Welcome": [],
    "authloginredirect": [],
    "authlogincallback": [],
    "authregister": [],
    "authvalidate": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
// declare module 'vue' {
//     interface ComponentCustomProperties {
//         route: typeof routeFn;
//     }
// }
