/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "Test": [],
    "authloginredirect": [],
    "authlogincallback": [],
    "authregister": [],
    "authvalidate": [],
    "authlogout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
